name: 每日句子更新

on:
  schedule:
    - cron: '0 9 * * *'  # 每天 UTC 时间 9 点触发
  workflow_dispatch: # 允许手动触发

jobs:
  update_daily_sentence:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 安装依赖
        run: |
          npm install axios

      - name: 获取每日句子并更新 Habitica
        run: |
          const axios = require('axios');

          async function getDailySentence() {
              const response = await axios.get("https://sentence.iciba.com/?c=dailysentence&m=getTodaySentence");
              return { content: response.data.content, translation: response.data.note };
          }

          async function updateHabiticaGroup(content, translation) {
              const url = "https://habitica.com/api/v3/groups/party";
              const headers = {
                  "x-api-user": process.env.HABITICA_USER_ID,
                  "x-api-key": process.env.HABITICA_API_KEY,
                  "Content-Type": "application/json"
              };
              const description = `### 一言 · A sentence of the day 🌹\n\n${content}\n\n${translation}\n\n#### Want to learn more about the party's purpose, rules, and other information? [Click here!](https://github.com/Delta-Water/Habitica-Party/blob/main/README.md)`;
              const data = { description };

              const response = await axios.put(url, data, { headers });
              return response.data;
          }

          (async () => {
              const { content, translation } = await getDailySentence();
              const result = await updateHabiticaGroup(content, translation);
              console.log(result);
          })();