name: 每日句子更新

on:
  schedule:
    - cron: '0 9 * * *'  # 每天 UTC 时间 9 点触发
  workflow_dispatch: # 允许手动触发

jobs:
  update_daily_sentence:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install requests

      - name: 获取每日句子并更新 Habitica
        run: |
          import os
          import requests

          # 获取每日句子
          response = requests.get("https://sentence.iciba.com/?c=dailysentence&m=getTodaySentence")
          response_data = response.json()
          content = response_data['content']
          translation = response_data['note']

          # 更新 Habitica 小组描述
          url = "https://habitica.com/api/v3/groups/party"
          headers = {
              "x-api-user": os.getenv("HABITICA_USER_ID"),
              "x-api-key": os.getenv("HABITICA_API_KEY"),
              "Content-Type": "application/json"
          }
          description = f"### 一言 · A sentence of the day 🌹\n\n{content}\n\n{translation}\n\n#### Want to learn more about the party's purpose, rules, and other information? [Click here!](https://github.com/Delta-Water/Habitica-Party/blob/main/README.md)"
          data = {"description": description}

          response = requests.put(url, headers=headers, json=data)
          print(response.json())