name: 队伍描述更新

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/5 * * * *'  # 每5分钟触发
  workflow_dispatch: # 允许手动触发

jobs:
  update_description:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          pip install requests

      - name: 执行更新脚本
        env:
          HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
          HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
        run: python scripts/update_description.py

      - name: 确认更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add log/Actions_timestamp.txt
          git commit -m "Update log/Actions_timestamp.txt from GitHub Actions"

      - name: 推送更改
        run: |
          git push